language: node_js
node_js:
- node
cache: yarn
script: yarn verify
deploy:
  - provider: heroku
    app: stackriot-styleguide
    api_key: $AUTHOR_HEROKU_KEY
  - provider: npm
    api_key: $AUTHOR_NPM_TOKEN
    email: $AUTHOR_EMAIL
    on:
      repo: stackriot/egghead-ui
      tags: true
      branch: master
notifications:
  email:
    on_success: never
    on_failure: always
