language: node_js
node_js:
- node
script: yarn
deploy:
  - provider: $DOKKU
    app: $DOKKU_APP
  # api_key: $API_BASE_URL
  - provider: npm
    api_key: $AUTHOR_NPM_TOKEN
    email: $AUTHOR_EMAIL
    on:
      repo: stackriot/egghead-ui
      tags: true
      branch: master
notifications:
  slack:
    on_success: always
    on_failure: always
