'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.sizes = exports.types = undefined;

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _lodash = require('lodash');

var _egghead = require('react-icons/lib/egghead');

var _fa = require('react-icons/lib/fa');

var _colors = require('../../utils/colors');

var _colors2 = _interopRequireDefault(_colors);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var typeToSvgIcon = {
  'accept': _egghead.EggheadAccept,
  'add': _egghead.EggheadPlus,
  'adjust': _fa.FaAdjust,
  'alert': _egghead.EggheadAlert,
  'align-center': _fa.FaAlignCenter,
  'align-justify': _fa.FaAlignJustify,
  'align-left': _fa.FaAlignLeft,
  'align-right': _fa.FaAlignRight,
  'angle-double-down': _fa.FaAngleDoubleDown,
  'angle-double-left': _fa.FaAngleDoubleLeft,
  'angle-double-right': _fa.FaAngleDoubleRight,
  'angle-double-up': _fa.FaAngleDoubleUp,
  'angle-down': _fa.FaAngleDown,
  'angle-left': _fa.FaAngleLeft,
  'angle-right': _fa.FaAngleRight,
  'angle-up': _fa.FaAngleUp,
  'apple': _fa.FaApple,
  'archive': _fa.FaArchive,
  'area-chart': _fa.FaAreaChart,
  'arrow-circle-down': _fa.FaArrowCircleDown,
  'arrow-circle-left': _fa.FaArrowCircleLeft,
  'arrow-circle-o-down': _fa.FaArrowCircleODown,
  'arrow-circle-o-left': _fa.FaArrowCircleOLeft,
  'arrow-circle-o-right': _fa.FaArrowCircleORight,
  'arrow-circle-o-up': _fa.FaArrowCircleOUp,
  'arrow-circle-right': _fa.FaArrowCircleRight,
  'arrow-circle-up': _fa.FaArrowCircleUp,
  'arrow-down': _egghead.EggheadArrowDown,
  'arrow-left': _egghead.EggheadArrowLeft,
  'arrow-right': _egghead.EggheadArrowRight,
  'arrow-up': _egghead.EggheadArrowUp,
  'arrows': _fa.FaArrows,
  'arrows-alt': _fa.FaArrowsAlt,
  'arrows-h': _fa.FaArrowsH,
  'arrows-v': _fa.FaArrowsV,
  'asterisk': _fa.FaAsterisk,
  'at': _fa.FaAt,
  'backward': _fa.FaBackward,
  'ban': _fa.FaBan,
  'bank': _fa.FaBank,
  'bar-chart': _fa.FaBarChart,
  'barcode': _fa.FaBarcode,
  'bars': _fa.FaBars,
  'birthday-cake': _fa.FaBirthdayCake,
  'bomb': _fa.FaBomb,
  'book': _fa.FaBook,
  'bookmark': _fa.FaBookmark,
  'bookmark-o': _fa.FaBookmarkO,
  'box': _fa.FaSquareO,
  'box-check': _fa.FaCheckSquareO,
  'bug': _fa.FaBug,
  'bullhorn': _fa.FaBullhorn,
  'bullseye': _fa.FaBullseye,
  'calculator': _fa.FaCalculator,
  'calendar': _fa.FaCalendar,
  'calendar-check-o': _fa.FaCalendarCheckO,
  'calendar-minus-o': _fa.FaCalendarMinusO,
  'calendar-o': _fa.FaCalendarO,
  'calendar-plus-o': _fa.FaCalendarPlusO,
  'calendar-times-o': _fa.FaCalendarTimesO,
  'camera': _fa.FaCamera,
  'camera-retro': _fa.FaCameraRetro,
  'cancel': _egghead.EggheadCross,
  'caret-down': _fa.FaCaretDown,
  'caret-left': _fa.FaCaretLeft,
  'caret-right': _fa.FaCaretRight,
  'caret-square-o-down': _fa.FaCaretSquareODown,
  'caret-square-o-left': _fa.FaCaretSquareOLeft,
  'caret-square-o-right': _fa.FaCaretSquareORight,
  'caret-square-o-up': _fa.FaCaretSquareOUp,
  'caret-up': _fa.FaCaretUp,
  'cart-arrow-down': _fa.FaCartArrowDown,
  'cart-plus': _fa.FaCartPlus,
  'certificate': _fa.FaCertificate,
  'chain': _fa.FaChain,
  'chain-broken': _fa.FaChainBroken,
  'check': _egghead.EggheadCheck,
  'check-circle': _fa.FaCheckCircle,
  'check-circle-o': _fa.FaCheckCircleO,
  'check-square': _fa.FaCheckSquare,
  'check-square-o': _fa.FaCheckSquareO,
  'check-watched': _egghead.EggheadCheckWatched,
  'chevron-circle-down': _fa.FaChevronCircleDown,
  'chevron-circle-left': _fa.FaChevronCircleLeft,
  'chevron-circle-right': _fa.FaChevronCircleRight,
  'chevron-circle-up': _fa.FaChevronCircleUp,
  'chevron-down': _fa.FaChevronDown,
  'chevron-left': _fa.FaChevronLeft,
  'chevron-right': _fa.FaChevronRight,
  'chevron-up': _fa.FaChevronUp,
  'chrome': _fa.FaChrome,
  'circle': _fa.FaCircle,
  'circle-arrow-down-outline': _egghead.EggheadCircleArrowDownOutline,
  'circle-o': _fa.FaCircleO,
  'circle-o-notch': _fa.FaCircleONotch,
  'circle-thin': _fa.FaCircleThin,
  'clipboard': _fa.FaClipboard,
  'clock': _fa.FaClockO,
  'clock-time': _egghead.EggheadClockTime,
  'clone': _fa.FaClone,
  'close': _fa.FaClose,
  'cloud': _fa.FaCloud,
  'cloud-download': _fa.FaCloudDownload,
  'cloud-upload': _fa.FaCloudUpload,
  'code': _fa.FaCode,
  'code-fork': _fa.FaCodeFork,
  'codepen': _fa.FaCodepen,
  'coffee': _fa.FaCoffee,
  'cog': _fa.FaCog,
  'cogs': _fa.FaCogs,
  'columns': _fa.FaColumns,
  'comment': _fa.FaComment,
  'comment-alert': _egghead.EggheadCommentAlert,
  'comment-o': _fa.FaCommentO,
  'commenting': _fa.FaCommenting,
  'commenting-o': _fa.FaCommentingO,
  'comments': _fa.FaComments,
  'comments-o': _fa.FaCommentsO,
  'compress': _fa.FaCompress,
  'copy': _fa.FaCopy,
  'copyright': _fa.FaCopyright,
  'course': _fa.FaFolderOpenO,
  'course-headline': _egghead.EggheadFullCoursesHeadline,
  'creative-commons': _fa.FaCreativeCommons,
  'credit-card': _fa.FaCreditCard,
  'credit-card-alt': _fa.FaCreditCardAlt,
  'crop': _fa.FaCrop,
  'crosshairs': _fa.FaCrosshairs,
  'css3': _fa.FaCss3,
  'cube': _fa.FaCube,
  'cubes': _fa.FaCubes,
  'cut': _fa.FaCut,
  'dashboard': _fa.FaDashboard,
  'database': _fa.FaDatabase,
  'dedent': _fa.FaDedent,
  'desktop': _fa.FaDesktop,
  'diamond': _fa.FaDiamond,
  'dollar': _fa.FaMoney,
  'dot-circle-o': _fa.FaDotCircleO,
  'download': _fa.FaDownload,
  'edit': _egghead.EggheadEdit,
  'eject': _fa.FaEject,
  'ellipsis-h': _fa.FaEllipsisH,
  'ellipsis-v': _fa.FaEllipsisV,
  'enter': _egghead.EggheadEnterSearch,
  'envelope': _fa.FaEnvelope,
  'envelope-o': _fa.FaEnvelopeO,
  'envelope-square': _fa.FaEnvelopeSquare,
  'eraser': _fa.FaEraser,
  'exchange': _fa.FaExchange,
  'exclamation': _fa.FaExclamation,
  'exclamation-circle': _fa.FaExclamationCircle,
  'exclamation-triangle': _fa.FaExclamationTriangle,
  'expand': _fa.FaExpand,
  'external-link': _fa.FaExternalLink,
  'external-link-square': _fa.FaExternalLinkSquare,
  'eye': _fa.FaEye,
  'eye-slash': _fa.FaEyeSlash,
  'eyedropper': _fa.FaEyedropper,
  'facebook': _egghead.EggheadFacebook,
  'fast-backward': _fa.FaFastBackward,
  'fast-forward': _fa.FaFastForward,
  'feed': _fa.FaFeed,
  'file': _fa.FaFile,
  'file-archive-o': _fa.FaFileArchiveO,
  'file-audio-o': _fa.FaFileAudioO,
  'file-code-o': _fa.FaFileCodeO,
  'file-excel-o': _fa.FaFileExcelO,
  'file-image-o': _fa.FaFileImageO,
  'file-movie-o': _fa.FaFileMovieO,
  'file-o': _fa.FaFileO,
  'file-pdf-o': _fa.FaFilePdfO,
  'file-powerpoint-o': _fa.FaFilePowerpointO,
  'file-text': _fa.FaFileText,
  'file-text-o': _fa.FaFileTextO,
  'file-word-o': _fa.FaFileWordO,
  'film': _fa.FaFilm,
  'filter': _fa.FaFilter,
  'flag': _egghead.EggheadFlag,
  'flag-checkered': _fa.FaFlagCheckered,
  'flag-o': _fa.FaFlagO,
  'flask': _fa.FaFlask,
  'floppy-o': _fa.FaFloppyO,
  'folder': _fa.FaFolder,
  'folder-language': _egghead.EggheadFolderLanguage,
  'folder-o': _fa.FaFolderO,
  'folder-open': _fa.FaFolderOpen,
  'folder-open-o': _fa.FaFolderOpenO,
  'font': _fa.FaFont,
  'forward': _fa.FaForward,
  'frown-o': _fa.FaFrownO,
  'futbol-o': _fa.FaFutbolO,
  'gavel': _fa.FaGavel,
  'gift': _fa.FaGift,
  'git': _fa.FaGit,
  'git-square': _fa.FaGitSquare,
  'github': _fa.FaGithub,
  'github-alt': _fa.FaGithubAlt,
  'glass': _fa.FaGlass,
  'globe': _fa.FaGlobe,
  'google': _fa.FaGoogle,
  'googlePlus': _fa.FaGooglePlus,
  'googlePlusSquare': _fa.FaGooglePlusSquare,
  'graduationCap': _fa.FaGraduationCap,
  'group': _fa.FaGroup,
  'hand-grab-o': _fa.FaHandGrabO,
  'hand-o-down': _fa.FaHandODown,
  'hand-o-left': _fa.FaHandOLeft,
  'hand-o-right': _fa.FaHandORight,
  'hand-o-up': _fa.FaHandOUp,
  'hashtag': _fa.FaHashtag,
  'hdd-o': _fa.FaHddO,
  'heart': _egghead.EggheadHeart,
  'help': _egghead.EggheadHelp,
  'history': _egghead.EggheadHistory,
  'home': _fa.FaHome,
  'hourglass': _fa.FaHourglass,
  'hourglass1': _fa.FaHourglass1,
  'hourglass2': _fa.FaHourglass2,
  'hourglass3': _fa.FaHourglass3,
  'hourglassO': _fa.FaHourglassO,
  'html5': _fa.FaHtml5,
  'iCursor': _fa.FaICursor,
  'image': _fa.FaImage,
  'inbox': _fa.FaInbox,
  'indent': _fa.FaIndent,
  'info': _egghead.EggheadInfo,
  'info-circle': _fa.FaInfoCircle,
  'instagram': _fa.FaInstagram,
  'italic': _fa.FaItalic,
  'jsfiddle': _fa.FaJsfiddle,
  'key': _fa.FaKey,
  'keyboard-o': _fa.FaKeyboardO,
  'laptop': _fa.FaLaptop,
  'leaf': _fa.FaLeaf,
  'lesson': _fa.FaFileO,
  'lesson-headline': _egghead.EggheadQuickLessonsHeadline,
  'lesson-play-playlist': _egghead.EggheadLessonPlayPlaylist,
  'level-down': _fa.FaLevelDown,
  'level-up': _fa.FaLevelUp,
  'lightbulb-o': _fa.FaLightbulbO,
  'line-chart': _fa.FaLineChart,
  'list': _fa.FaList,
  'list-alt': _fa.FaListAlt,
  'list-ol': _fa.FaListOl,
  'list-ul': _fa.FaListUl,
  'locationArrow': _fa.FaLocationArrow,
  'lock': _fa.FaLock,
  'long-arrow-down': _fa.FaLongArrowDown,
  'long-arrow-left': _fa.FaLongArrowLeft,
  'long-arrow-right': _fa.FaLongArrowRight,
  'long-arrow-up': _fa.FaLongArrowUp,
  'magic': _fa.FaMagic,
  'magnet': _fa.FaMagnet,
  'mail': _egghead.EggheadMail,
  'mail-forward': _fa.FaMailForward,
  'mail-reply': _fa.FaMailReply,
  'mail-reply-all': _fa.FaMailReplyAll,
  'map': _fa.FaMap,
  'map-pin': _fa.FaMapPin,
  'map-signs': _fa.FaMapSigns,
  'meh-o': _fa.FaMehO,
  'menu': _fa.FaBars,
  'microphone': _fa.FaMicrophone,
  'microphone-slash': _fa.FaMicrophoneSlash,
  'minus': _fa.FaMinus,
  'minus-circle': _fa.FaMinusCircle,
  'minus-square': _fa.FaMinusSquare,
  'minus-square-o': _fa.FaMinusSquareO,
  'mobile': _fa.FaMobile,
  'money': _fa.FaMoney,
  'moon-o': _fa.FaMoonO,
  'mouse-pointer': _fa.FaMousePointer,
  'music': _fa.FaMusic,
  'newspaper-o': _fa.FaNewspaperO,
  'object-group': _fa.FaObjectGroup,
  'object-ungroup': _fa.FaObjectUngroup,
  'paper-plane': _fa.FaPaperPlane,
  'paper-plane-o': _fa.FaPaperPlaneO,
  'paperclip': _fa.FaPaperclip,
  'paragraph': _fa.FaParagraph,
  'pause': _fa.FaPause,
  'pause-circle': _fa.FaPauseCircle,
  'pause-circle-o': _fa.FaPauseCircleO,
  'pencil': _fa.FaPencil,
  'pencil-square': _fa.FaPencilSquare,
  'percent': _fa.FaPercent,
  'phone': _fa.FaPhone,
  'phone-square': _fa.FaPhoneSquare,
  'pie-chart': _fa.FaPieChart,
  'play': _egghead.EggheadPlay,
  'playbook': _egghead.EggheadPlaybook,
  'play-course': _egghead.EggheadPlayCourse,
  'play-lesson': _egghead.EggheadPlayLesson,
  'plug': _fa.FaPlug,
  'plus-circle': _fa.FaPlusCircle,
  'plus-square': _fa.FaPlusSquare,
  'plus-square-o': _fa.FaPlusSquareO,
  'print': _fa.FaPrint,
  'profile': _egghead.EggheadProfile,
  'progress-ring': _egghead.EggheadProgressRing,
  'question': _egghead.EggheadQuestion,
  'question-circle': _fa.FaQuestionCircle,
  'question-circle-o': _fa.FaQuestionCircleO,
  'quote-left': _fa.FaQuoteLeft,
  'quote-right': _fa.FaQuoteRight,
  'recycle': _fa.FaRecycle,
  'refresh': _egghead.EggheadRefresh,
  'registered': _fa.FaRegistered,
  'remove': _fa.FaMinusCircle,
  'repeat': _fa.FaRepeat,
  'reply': _fa.FaMailReply,
  'request': _egghead.EggheadRequest,
  'retweet': _fa.FaRetweet,
  'revise': _egghead.EggheadRevise,
  'rotate-left': _fa.FaRotateLeft,
  'rss': _egghead.EggheadRss,
  'rss-square': _fa.FaRssSquare,
  'search': _fa.FaSearch,
  'search-minus': _fa.FaSearchMinus,
  'search-plus': _fa.FaSearchPlus,
  'server': _fa.FaServer,
  'share': _fa.FaShareAlt,
  'share-alt': _fa.FaShareAlt,
  'share-alt-square': _fa.FaShareAltSquare,
  'share-square': _fa.FaShareSquare,
  'share-square-o': _fa.FaShareSquareO,
  'shopping-cart': _fa.FaShoppingCart,
  'sign-out': _egghead.EggheadSignOut,
  'sign-in': _fa.FaSignIn,
  'signal': _fa.FaSignal,
  'sitemap': _fa.FaSitemap,
  'slack': _fa.FaSlack,
  'sliders': _fa.FaSliders,
  'smile-o': _fa.FaSmileO,
  'sort': _fa.FaSort,
  'sort-alpha-asc': _fa.FaSortAlphaAsc,
  'sort-alpha-desc': _fa.FaSortAlphaDesc,
  'sort-amount-asc': _fa.FaSortAmountAsc,
  'sort-amount-desc': _fa.FaSortAmountDesc,
  'sort-asc': _fa.FaSortAsc,
  'sort-desc': _fa.FaSortDesc,
  'sort-numeric-asc': _fa.FaSortNumericAsc,
  'sort-numeric-desc': _fa.FaSortNumericDesc,
  'spinner': _fa.FaSpinner,
  'square': _fa.FaSquare,
  'star': _fa.FaStar,
  'star-fill': _egghead.EggheadStarFill,
  'star-outline': _egghead.EggheadStarOutline,
  'star-half': _fa.FaStarHalf,
  'star-half-empty': _fa.FaStarHalfEmpty,
  'star-o': _fa.FaStarO,
  'stats': _egghead.EggheadStats,
  'step-backward': _fa.FaStepBackward,
  'step-forward': _fa.FaStepForward,
  'sticky-note': _fa.FaStickyNote,
  'sticky-note-o': _fa.FaStickyNoteO,
  'stop': _fa.FaStop,
  'stop-circle': _fa.FaStopCircle,
  'stop-circle-o': _fa.FaStopCircleO,
  'success': _fa.FaCheckCircle,
  'sun-o': _fa.FaSunO,
  'table': _fa.FaTable,
  'tablet': _fa.FaTablet,
  'tag': _fa.FaTag,
  'tags': _fa.FaTags,
  'tasks': _fa.FaTasks,
  'technology': _egghead.EggheadTechnology,
  'television': _fa.FaTelevision,
  'terminal': _fa.FaTerminal,
  'text-height': _fa.FaTextHeight,
  'text-width': _fa.FaTextWidth,
  'th': _fa.FaTh,
  'th-large': _fa.FaThLarge,
  'th-list': _fa.FaThList,
  'thumb-tack': _fa.FaThumbTack,
  'thumbs-down': _egghead.EggheadThumbsDown,
  'thumbs-up': _egghead.EggheadThumbsUp,
  'thumbs-o-down': _fa.FaThumbsODown,
  'thumbs-o-up': _fa.FaThumbsOUp,
  'ticket': _fa.FaTicket,
  'timer-plus': _egghead.EggheadTimerPlus,
  'times-circle': _fa.FaTimesCircle,
  'times-circle-o': _fa.FaTimesCircleO,
  'toggle-off': _fa.FaToggleOff,
  'toggle-on': _fa.FaToggleOn,
  'trademark': _fa.FaTrademark,
  'trash': _fa.FaTrash,
  'trash-o': _fa.FaTrashO,
  'tree': _fa.FaTree,
  'trophy': _fa.FaTrophy,
  'twitter': _egghead.EggheadTwitter,
  'twitter-square': _fa.FaTwitterSquare,
  'underline': _fa.FaUnderline,
  'universal-access': _fa.FaUniversalAccess,
  'unlock': _fa.FaUnlock,
  'unlock-alt': _fa.FaUnlockAlt,
  'update': _egghead.EggheadUpdate,
  'upload': _egghead.EggheadUpload,
  'upload-cloud': _egghead.EggheadUploadCloud,
  'usb': _fa.FaUsb,
  'user': _fa.FaUser,
  'user-plus': _fa.FaUserPlus,
  'user-times': _fa.FaUserTimes,
  'video-camera': _fa.FaVideoCamera,
  'vimeo-square': _fa.FaVimeoSquare,
  'volume-control-phone': _fa.FaVolumeControlPhone,
  'volume-down': _fa.FaVolumeDown,
  'volume-off': _fa.FaVolumeOff,
  'volume-up': _fa.FaVolumeUp,
  'warning': _fa.FaExclamationCircle,
  'wheelchair': _fa.FaWheelchair,
  'wheelchairAlt': _fa.FaWheelchairAlt,
  'wifi': _fa.FaWifi,
  'windows': _fa.FaWindows,
  'wrench': _fa.FaWrench
};

var types = exports.types = (0, _lodash.keys)(typeToSvgIcon);

var sizeToClass = {
  1: 'f1',
  2: 'f2',
  3: 'f3',
  4: 'f4',
  5: 'f5',
  6: 'f6'
};

var sizes = exports.sizes = (0, _lodash.keys)(sizeToClass);

var Icon = function Icon(_ref) {
  var type = _ref.type,
      size = _ref.size,
      color = _ref.color;

  var DynamicIcon = typeToSvgIcon[type];
  return _react2.default.createElement(DynamicIcon, { className: sizeToClass[size] + ' ' + color });
};

Icon.propTypes = {
  type: _react.PropTypes.oneOf(types).isRequired,
  size: _react.PropTypes.oneOf(sizes),
  color: _react.PropTypes.oneOf(_colors2.default)
};

Icon.defaultProps = {
  size: '3',
  color: 'dark-gray'
};

exports.default = Icon;